[2023-12-22 21:54:19 +0200] [333347] [INFO] Starting gunicorn 21.2.0
[2023-12-22 21:54:19 +0200] [333347] [INFO] Listening at: http://127.0.0.1:8000 (333347)
[2023-12-22 21:54:19 +0200] [333347] [INFO] Using worker: sync
[2023-12-22 21:54:19 +0200] [333348] [INFO] Booting worker with pid: 333348
Failed to find attribute 'app' in 'app'.
[2023-12-22 21:54:19 +0200] [333348] [INFO] Worker exiting (pid: 333348)
[2023-12-22 21:54:19 +0200] [333347] [ERROR] Worker (pid:333348) exited with code 4
[2023-12-22 21:54:19 +0200] [333347] [ERROR] Shutting down: Master
[2023-12-22 21:54:19 +0200] [333347] [ERROR] Reason: App failed to load.
[2023-12-22 22:44:39 +0200] [334481] [INFO] Starting gunicorn 21.2.0
[2023-12-22 22:44:39 +0200] [334481] [INFO] Listening at: http://0.0.0.0:9500 (334481)
[2023-12-22 22:44:39 +0200] [334481] [INFO] Using worker: sync
[2023-12-22 22:44:39 +0200] [334482] [INFO] Booting worker with pid: 334482
[2023-12-22 22:44:39 +0200] [334483] [INFO] Booting worker with pid: 334483
[2023-12-22 23:13:05 +0200] [334481] [INFO] Handling signal: term
[2023-12-22 23:13:05 +0200] [334482] [INFO] Worker exiting (pid: 334482)
[2023-12-22 23:13:05 +0200] [334483] [INFO] Worker exiting (pid: 334483)
[2023-12-22 23:13:05 +0200] [334481] [INFO] Shutting down: Master
[2023-12-22 23:13:35 +0200] [335071] [INFO] Starting gunicorn 21.2.0
[2023-12-22 23:13:35 +0200] [335071] [INFO] Listening at: http://0.0.0.0:9500 (335071)
[2023-12-22 23:13:35 +0200] [335071] [INFO] Using worker: sync
[2023-12-22 23:13:35 +0200] [335072] [INFO] Booting worker with pid: 335072
[2023-12-22 23:13:36 +0200] [335073] [INFO] Booting worker with pid: 335073
[2023-12-22 23:13:36 +0200] [335072] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rugema3/stock_management_system/app.py", line 10, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-12-22 23:13:36 +0200] [335072] [INFO] Worker exiting (pid: 335072)
[2023-12-22 23:13:36 +0200] [335073] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rugema3/globalpayhub/airtime/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rugema3/stock_management_system/app.py", line 10, in <module>
    from decouple import config
ModuleNotFoundError: No module named 'decouple'
[2023-12-22 23:13:36 +0200] [335073] [INFO] Worker exiting (pid: 335073)
[2023-12-22 23:13:36 +0200] [335071] [ERROR] Worker (pid:335072) exited with code 3
[2023-12-22 23:13:36 +0200] [335071] [ERROR] Worker (pid:335073) was sent SIGTERM!
[2023-12-22 23:13:36 +0200] [335071] [ERROR] Shutting down: Master
[2023-12-22 23:13:36 +0200] [335071] [ERROR] Reason: Worker failed to boot.
[2023-12-22 23:15:21 +0200] [335111] [INFO] Starting gunicorn 21.2.0
[2023-12-22 23:15:21 +0200] [335111] [INFO] Listening at: http://0.0.0.0:9500 (335111)
[2023-12-22 23:15:21 +0200] [335111] [INFO] Using worker: sync
[2023-12-22 23:15:21 +0200] [335112] [INFO] Booting worker with pid: 335112
[2023-12-22 23:15:21 +0200] [335113] [INFO] Booting worker with pid: 335113
[2023-12-22 23:17:29 +0200] [335111] [CRITICAL] WORKER TIMEOUT (pid:335113)
[2023-12-22 23:17:29 +0200] [335113] [INFO] Worker exiting (pid: 335113)
User data: (12, 'charles@gmail.com', '123', 'it', 'admin')
[2023-12-22 23:17:29 +0200] [335111] [ERROR] Worker (pid:335113) exited with code 1
[2023-12-22 23:17:29 +0200] [335111] [ERROR] Worker (pid:335113) exited with code 1.
[2023-12-22 23:17:29 +0200] [335144] [INFO] Booting worker with pid: 335144
[2023-12-22 23:17:48 +0200] [335111] [INFO] Handling signal: term
[2023-12-22 23:17:48 +0200] [335112] [INFO] Worker exiting (pid: 335112)
User role: admin
[2023-12-22 23:17:48 +0200] [335144] [INFO] Worker exiting (pid: 335144)
[2023-12-22 23:17:49 +0200] [335111] [INFO] Shutting down: Master
[2023-12-22 23:18:27 +0200] [335175] [INFO] Starting gunicorn 21.2.0
[2023-12-22 23:18:27 +0200] [335175] [INFO] Listening at: http://0.0.0.0:9500 (335175)
[2023-12-22 23:18:27 +0200] [335175] [INFO] Using worker: sync
[2023-12-22 23:18:27 +0200] [335176] [INFO] Booting worker with pid: 335176
[2023-12-22 23:18:27 +0200] [335177] [INFO] Booting worker with pid: 335177
[2023-12-22 23:23:09 +0200] [335175] [INFO] Handling signal: term
[2023-12-22 23:23:09 +0200] [335176] [INFO] Worker exiting (pid: 335176)
User role: admin
[2023-12-22 23:23:09 +0200] [335177] [INFO] Worker exiting (pid: 335177)
[2023-12-22 23:23:09 +0200] [335175] [INFO] Shutting down: Master
[2023-12-22 23:23:45 +0200] [335297] [INFO] Starting gunicorn 21.2.0
[2023-12-22 23:23:45 +0200] [335297] [INFO] Listening at: http://0.0.0.0:9500 (335297)
[2023-12-22 23:23:45 +0200] [335297] [INFO] Using worker: sync
[2023-12-22 23:23:45 +0200] [335298] [INFO] Booting worker with pid: 335298
[2023-12-22 23:23:45 +0200] [335299] [INFO] Booting worker with pid: 335299
[2023-12-22 23:25:07 +0200] [335297] [CRITICAL] WORKER TIMEOUT (pid:335298)
[2023-12-22 23:25:07 +0200] [335298] [INFO] Worker exiting (pid: 335298)
[2023-12-22 23:25:08 +0200] [335297] [ERROR] Worker (pid:335298) exited with code 1
[2023-12-22 23:25:08 +0200] [335297] [ERROR] Worker (pid:335298) exited with code 1.
[2023-12-22 23:25:08 +0200] [335306] [INFO] Booting worker with pid: 335306
[2023-12-25 10:16:10 +0200] [335306] [WARNING] Invalid request from ip=212.70.149.146: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
[2023-12-25 10:39:13 +0200] [335299] [WARNING] Invalid request from ip=212.70.149.146: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
[2023-12-25 11:00:54 +0200] [335299] [WARNING] Invalid request from ip=212.70.149.146: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
[2023-12-25 11:21:47 +0200] [335306] [WARNING] Invalid request from ip=212.70.149.146: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
[2023-12-25 21:22:49 +0200] [335306] [WARNING] Invalid request from ip=5.181.86.12: Invalid HTTP request line: '\x03\x00\x00/*à\x00\x00\x00\x00\x00Cookie: mstshash=Administr'
[2023-12-26 12:17:30 +0200] [335297] [CRITICAL] WORKER TIMEOUT (pid:335306)
[2023-12-26 12:17:30 +0200] [335306] [INFO] Worker exiting (pid: 335306)
[2023-12-26 12:17:31 +0200] [335297] [ERROR] Worker (pid:335306) exited with code 1
[2023-12-26 12:17:31 +0200] [335297] [ERROR] Worker (pid:335306) exited with code 1.
[2023-12-26 12:17:31 +0200] [395678] [INFO] Booting worker with pid: 395678
[2023-12-26 12:17:32 +0200] [395678] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 302, in _open_connection
    self._cmysql.connect(**cnx_kwargs)
_mysql_connector.MySQLInterfaceError: Can't connect to MySQL server on 'localhost:3306' (111)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/gunicorn/arbiter.py", line 609, in spawn_worker
    worker.init_process()
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/gunicorn/util.py", line 371, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/rugema3/stock_management_system/app.py", line 43, in <module>
    db = Database(db_config)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/rugema3/stock_management_system/application/models/database_manager.py", line 25, in __init__
    self.db_connection = mysql.connector.connect(**db_config)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/mysql/connector/pooling.py", line 293, in connect
    return CMySQLConnection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 128, in __init__
    self.connect(**kwargs)
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/mysql/connector/abstracts.py", line 1217, in connect
    self._open_connection()
  File "/home/rugema3/stock_management_system/stock/lib/python3.11/site-packages/mysql/connector/connection_cext.py", line 307, in _open_connection
    raise get_mysql_exception(
mysql.connector.errors.DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (111)
[2023-12-26 12:17:32 +0200] [395678] [INFO] Worker exiting (pid: 395678)
[2023-12-26 12:17:33 +0200] [335297] [ERROR] Worker (pid:395678) exited with code 3
[2023-12-26 12:17:33 +0200] [335299] [INFO] Worker exiting (pid: 335299)
[2023-12-26 12:17:33 +0200] [335297] [ERROR] Shutting down: Master
[2023-12-26 12:17:33 +0200] [335297] [ERROR] Reason: Worker failed to boot.
